{
 "title": "VCSA health",
 "tags": [
  "demo",
  "vsphere",
  "vcsa"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "vcsa",
    "label": "VCSA",
    "query": "show tag values with key = \"server\""
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Appliance",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "health_system",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_server",
     "measurement": "appliance_info",
     "select": [
      [
       { "params": [ "version" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "measurement": "cpu",
     "query": "SELECT (mean(\"used\") / mean(\"totalsize\"))*100 FROM \"storage.root\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "MEM Util",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "measurement": "mem",
     "query": "SELECT (mean(\"used\") / mean(\"totalsize\"))*100 FROM \"storage.root\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "measurement": "appliance_info",
     "query": "SELECT (mean(\"used\") / mean(\"totalsize\"))*100 FROM \"storage.root\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "Last check",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "measurement": "health_system",
     "query": "SELECT (mean(\"used\") / mean(\"totalsize\"))*100 FROM \"storage.root\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "System health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "health_system",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "health_load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "Mem health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "health_mem",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "Applmgmt health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "health_applmgmt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "health_storage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "DB storage health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "health_databasestorage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "vpxd",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcservice_vpxd",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "vpxd-svcs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcservice_vpxd-svcs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "vpostgres",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcservice_vmware-vpostgres",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "sso",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcservice_pschealth",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "sps",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcservice_sps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "ui",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vcservice_vsphere-ui",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  { "title": "Storage status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Storage root",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "targets": [
    {
     "measurement": "storage.root",
     "query": "SELECT (mean(\"used\") / mean(\"totalsize\"))*100 FROM \"storage.root\" WHERE $timeFilter and \"server\" =~ /$vcsa/",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage log",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "targets": [
    {
     "measurement": "storage.root",
     "query": "SELECT (mean(\"used\") / mean(\"totalsize\"))*100 FROM \"storage.log\" WHERE $timeFilter and \"server\" =~ /$vcsa/",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage core",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "targets": [
    {
     "measurement": "storage.root",
     "query": "SELECT (mean(\"used\") / mean(\"totalsize\"))*100 FROM \"storage.core\" WHERE $timeFilter and \"server\" =~ /$vcsa/",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage dblog",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "targets": [
    {
     "measurement": "storage.root",
     "query": "SELECT (mean(\"used\") / mean(\"totalsize\"))*100 FROM \"storage.dblog\" WHERE $timeFilter and \"server\" =~ /$vcsa/",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage db",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "targets": [
    {
     "measurement": "storage.root",
     "query": "SELECT (mean(\"used\") / mean(\"totalsize\"))*100 FROM \"storage.db\" WHERE $timeFilter and \"server\" =~ /$vcsa/",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage seat",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "targets": [
    {
     "measurement": "storage.root",
     "query": "SELECT (mean(\"used\") / mean(\"totalsize\"))*100 FROM \"storage.seat\" WHERE $timeFilter and \"server\" =~ /$vcsa/",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU/MEM",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "DB Storage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "alias": "$measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "storage.seat",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    },
    {
     "alias": "$measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "storage.log",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    },
    {
     "alias": "$measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "storage.core",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  { "title": "Available Update", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "appliance_update",
     "select": [
      [
       { "params": [ "new_version" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "Release date",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 25 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "measurement": "appliance_update",
     "select": [
      [
       { "params": [ "rel_date" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "Update type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "appliance_update",
     "select": [
      [
       { "params": [ "upd_type" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "Severity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "appliance_update",
     "select": [
      [
       { "params": [ "severity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "Priority",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "appliance_update",
     "select": [
      [
       { "params": [ "priority" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "Query time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 25 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "measurement": "appliance_update",
     "select": [
      [
       { "params": [ "query_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  { "title": "Backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "appliance_backup_job",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "Time (start)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 29 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "measurement": "appliance_backup_job",
     "select": [
      [
       { "params": [ "start" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 29 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "measurement": "appliance_backup_job",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "Schedule",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 29 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "measurement": "appliance_backup_schedule",
     "select": [
      [
       { "params": [ "schedEnabled" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "Recurrence",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 29 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "measurement": "appliance_backup_schedule",
     "select": [
      [
       { "params": [ "recurrence" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "Protocol",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 29 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "measurement": "appliance_backup_schedule",
     "select": [
      [
       { "params": [ "protocol" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  },
  {
   "title": "Host",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "appliance_backup_schedule",
     "select": [
      [
       { "params": [ "location" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcsa$/" }
     ]
    }
   ]
  }
 ]
}