{
 "title": "VCSA Health",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "vcenter",
    "label": "vCenter",
    "query": "show tag values with key = \"server\""
   }
  ]
 },
 "panels": [
  { "title": "$vcenter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "vcenter" },
  {
   "title": "CPU Util",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "MEM Util",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "MEM Util",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "Appl mgmt",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_applmgmt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "DB Storage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_databasestorage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "Mem",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_mem",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "Software packages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_softwarepackages",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_storage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_swap",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "health_system",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "Applmgmt",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vcservice_applmgmt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "PSC Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vcservice_pschealth",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "Statsmonitor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vcservice_statsmonitor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "Update Manager",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vcservice_updatemgr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "vAPI Endpoint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vcservice_vapi-endpoint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "vPostgres",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vcservice_vmware-vpostgres",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "vSAN-Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vcservice_vsan-health",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "vSphere-UI",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vcservice_vsphere-ui",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  }
 ]
}