{
 "title": "VSAN Overview",
 "tags": [
  "vsan",
  "vsphere",
  "storage"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "VSAN",
    "query": "SHOW TAG VALUES WITH KEY = \"san\" WHERE \"type\" = 'vsan'"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vsan_diskusage",
     "select": [
      [
       { "params": [ "capacity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Freespace",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "vsan_diskusage",
     "select": [
      [
       { "params": [ "freespace" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "san", "operator": "=~", "value": "/^$VSAN$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "vsan" }
     ]
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "vsan_diskusage",
     "select": [
      [
       { "params": [ "vdiskusage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "VSAN Overhead",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "vsan_diskusage",
     "select": [
      [
       { "params": [ "vsanoverhead" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Frontend  Read Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "KBs",
   "valueName": "current",
   "targets": [
    {
     "measurement": "kB_read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Frontend Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "measurement": "latency_read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Frontend Write Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "format": "KBs",
   "valueName": "current",
   "targets": [
    {
     "measurement": "kB_write",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Frontend Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "measurement": "latency_write",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend Read Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "format": "KBs",
   "valueName": "current",
   "targets": [
    {
     "measurement": "kB_read_backend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "measurement": "latency_read_backend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend Write Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "format": "KBs",
   "valueName": "current",
   "targets": [
    {
     "measurement": "kB_write_backend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "measurement": "latency_write_backend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "[[tag_san]]_frontend",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "san" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kB_read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    },
    {
     "alias": "[[tag_san]]_backend",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "san" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kB_read_backend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "[[tag_san]]_frontend",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "san" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kB_write",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    },
    {
     "alias": "[[tag_san]]_backend",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "san" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kB_write_backend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_san]]_frontend",
     "groupBy": [
      { "params": [ "san" ], "type": "tag" }
     ],
     "measurement": "latency_read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    },
    {
     "alias": "[[tag_san]]_backend",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "san" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "latency_read_backend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_san]]_frontend",
     "groupBy": [
      { "params": [ "san" ], "type": "tag" }
     ],
     "measurement": "latency_write",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    },
    {
     "alias": "[[tag_san]]_backend",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "san" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "latency_write_backend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Congestion",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_san]]_frontend",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "san" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "congestion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    },
    {
     "alias": "[[tag_san]]_backend",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "san" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "congestion_backend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Outstanding IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "[[tag_san]]_frontend",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "san" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io_outstanding",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    },
    {
     "alias": "[[tag_san]]_backend",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "san" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io_outstanding_backend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_san]]_$col",
     "groupBy": [
      { "params": [ "san" ], "type": "tag" }
     ],
     "measurement": "vsan_diskusage",
     "select": [
      [
       { "params": [ "freespace" ], "type": "field" }
      ],
      [
       { "params": [ "primaryvmdata" ], "type": "field" }
      ],
      [
       { "params": [ "vdiskusage" ], "type": "field" }
      ],
      [
       { "params": [ "vsanoverhead" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  }
 ]
}