{
 "title": "VSAN Backend",
 "tags": [
  "vsan",
  "vsphere",
  "storage"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "VSAN",
    "query": "SHOW TAG VALUES WITH KEY = \"san\" WHERE \"type\" = 'vsan'"
   }
  ]
 },
 "panels": [
  {
   "title": "Read Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "KBs",
   "valueName": "current",
   "targets": [
    {
     "measurement": "kB_read_backend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "measurement": "latency_read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "KBs",
   "valueName": "current",
   "targets": [
    {
     "measurement": "kB_write_backend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "measurement": "latency_write_backend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Resync Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "measurement": "latency_resync_read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovery IO Write",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "format": "iops",
   "valueName": "max",
   "targets": [
    {
     "measurement": "io_write_recovery",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovery Write Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "format": "KBs",
   "valueName": "max",
   "targets": [
    {
     "measurement": "kb_write_recovery",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovery Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "measurement": "latency_write_recovery",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_san",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "san" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kB_read_backend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_san",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "san" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kB_write_backend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_san",
     "groupBy": [
      { "params": [ "san" ], "type": "tag" }
     ],
     "measurement": "latency_read_backend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_san",
     "groupBy": [
      { "params": [ "san" ], "type": "tag" }
     ],
     "measurement": "latency_write_backend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Congestion",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_san",
     "groupBy": [
      { "params": [ "san" ], "type": "tag" }
     ],
     "measurement": "congestion_backend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Outstanding IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_san",
     "groupBy": [
      { "params": [ "san" ], "type": "tag" }
     ],
     "measurement": "io_outstanding_backend",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend Resync Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_san",
     "groupBy": [
      { "params": [ "san" ], "type": "tag" }
     ],
     "measurement": "latency_resync_read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovery IO Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_san",
     "groupBy": [
      { "params": [ "san" ], "type": "tag" }
     ],
     "measurement": "io_write_recovery",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovery Throughput Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_san",
     "groupBy": [
      { "params": [ "san" ], "type": "tag" }
     ],
     "measurement": "kb_write_recovery",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovery Latency Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_san",
     "groupBy": [
      { "params": [ "san" ], "type": "tag" }
     ],
     "measurement": "latency_write_recovery",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan" },
      { "condition": "AND", "key": "san", "operator": "=~", "value": "/^$VSAN$/" }
     ]
    }
   ]
  }
 ]
}