{
 "title": "VSAN Diskgroup",
 "tags": [
  "storage",
  "vsphere",
  "vsan"
 ],
 "time": { "from": "now-1h", "to": "now-5m" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "san",
    "label": "VSAN",
    "query": "SHOW TAG VALUES WITH KEY = \"san\" WHERE \"type\" = 'vsan'"
   },
   {
    "name": "diskgroup",
    "label": "Diskgroup",
    "query": "SHOW TAG VALUES WITH KEY = \"name\" WHERE \"type\" = 'vsan_diskgroup' and \"host\" =~ /$host/"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\" WHERE \"type\" = 'vsan_diskgroup' and \"san\" =~ /$san/"
   }
  ]
 },
 "panels": [
  {
   "title": "Diskgroups",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "capacity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan_diskgroup" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$diskgroup$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "VMs",
   "type": "singlestat",
   "description": "VM count on the selected host(s)",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vm" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "singlestat",
   "description": "Average capacity of the diskgroup(s)",
   "gridPos": { "h": 3, "w": 10, "x": 11, "y": 0 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "capacity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan_diskgroup" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$diskgroup$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "KBs",
   "valueName": "max",
   "targets": [
    {
     "measurement": "kB_read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan_diskgroup" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$diskgroup$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "measurement": "latency_read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan_diskgroup" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$diskgroup$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "format": "KBs",
   "valueName": "max",
   "targets": [
    {
     "measurement": "kB_write",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan_diskgroup" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$diskgroup$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "ms",
   "valueName": "max",
   "targets": [
    {
     "measurement": "latency_write",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan_diskgroup" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$diskgroup$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kB_read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan_diskgroup" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$diskgroup$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kB_write",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan_diskgroup" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$diskgroup$/" }
     ]
    }
   ]
  },
  {
   "title": "Read IOps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io_read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan_diskgroup" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$diskgroup$/" }
     ]
    }
   ]
  },
  {
   "title": "Write IOps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "io_write",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan_diskgroup" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$diskgroup$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "latency_read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan_diskgroup" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$diskgroup$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "latency_write",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan_diskgroup" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$diskgroup$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Cache Read Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "latency_readcache_read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan_diskgroup" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$diskgroup$/" }
     ]
    }
   ]
  },
  {
   "title": "Writebuffer Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "latency_writebuffer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "vsan_diskgroup" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$diskgroup$/" }
     ]
    }
   ]
  }
 ]
}